my_cred='C:/streamlit/phrasal-indexer-393802-bfefa4c104fc.json'
my_bucket='csac_final_v2'

clova_id = "l9maed2fj4"
client_secret = "A6g38ZJkOwQiV5c4hj3ycZyzjEg9QtavPnqoCaFX"
clova_data="speaker=nara&volume=0&speed=0&pitch=0&format=mp3&text="
clova_url = "https://naveropenapi.apigw.ntruss.com/tts-premium/v1/tts"

bucket_path="gs://csac_final_v2/new/"

replicate_api_token = "r8_5lJEVWYy7MMARP3qpVcrrY4yByx8oM32lV6RF"
img_generator_1 = "ryan-koo92/sdxl-ip:530e6d94142dc71729cfb592499c81ba511b3c289c08cece5cb686a764f91862"
img_generator_2 = "ryan-koo92/sdxl-sr:121c2f6a3bbb85b9f34430565fc3b0398a3b4b469e2179fcd6210638089feab0"
multimodal_llm = "joehoover/mplug-owl:51a43c9d00dfd92276b2511b509fcb3ad82e221f6a9e5806c54e69803e291d6b"
img_prompt = 'This image is an art painting, and please describe this art painting in the order below. First, describe its genre. Genre refers to the subject matter and objects depicted. Second, describe its media. Media refers to materials the artwork is made from, and to techniques used by the artist to create that artwork.  Third, describe its style. Style refers to its distinctive visual elements, techniques and methods. And finally, describe this art painting as visually accurate as possible.'

deepl_api ='2fc1546f-1428-6006-bf76-feaf45564fb0:fx'

clova_id_2 = 'kcl33iujct'
clova_secrets_2 = 'yLC9VzREQcPNu8w4Quy6tg8UiWa6BxGLt9AhqSeT'

openai_api = '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'

[connection.gcs]
type="service_account"
project_id="phrasal-indexer-393802"
private_key_id="bfefa4c104fc945b9edde7b3b42bce69d8fd4159"
private_key="-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCn20If4j79UQ5W\nYTaneW3+lnyqp6SkOptbZz/lf57eJGEjtooYPySEXKUFuJ2aPdSUr+Ze8tNiLBAM\niN7J8O5AiclB+KWHlKCKBzmN3guhhZ/uod9yomNAI7szA7O2x8ZlxTaACcIogsku\n8WxFp5EHoqEC3FpPKVIdyARC9SQ2MAwltlDFCryP4MK2NdEsk7kr8mACN2ymg1J8\nAL6PuzlVPA8YI0GcybtBUMGdAtV/amBnSSPydR4632B9MuAA7C/Ax8gWVN9DT5+e\n3uMZI9FTyK4SrYiuIKWzSf1TYyuw54bskW9lVLnBll6hslDF0vAABzX7EFY9Kz2r\nYtdzB1MXAgMBAAECggEACrmMTLPh88F9ZFuAaHbuZjkrQflwIDt2YwKtJyFeVIcy\nhbD2EH0y/MSxQ9+l1423ysA/vIql+Dx50giKDju3R/xbFZH+Jt7Xhbosco9guDNC\nIrceVcQLtLS+aJCwp4RgKBnPqk1Kpdf6uWXHgIknpRCTr7ZwjA+ceuFQFGR2qdeR\nXqns57qD6cqme2/hlHj1g1/bqt1FnKAL4hcyeg6KLsCu2vbrKY51Wg3zMX0LLRBL\nYlmWIsoqk123n0gY27X7L/VYI74k/Ra4o/Evjytl/ziMINRW9Gb7ptGGohbHv2Wh\nHE64m3gFOzRJvQW35d1G3bNWss/Y7AVniXxFt1PhwQKBgQDqWpUtOzI/9v2eOIOa\n1oN7vtGFbdPjf1R//UH8h/DVomtxKhJUJ2So2QH70tzxy7CcVSIjbpgd4mA327YN\nZuZNTf4Rk2eKs6xvjU3Kgw1e96p8WiG6MjEaSph53sz2cZybDdxv0hM18MIn0jPK\nOToSk/s9iCL9dWvcZNR85Pmk8QKBgQC3XE+rfKzwP8wEH7ojfARMfH3hi7tCHlGO\nv0fASF7Qmx9YIiCxbxm8lLHmolAnzUW94IgOt3G5iYKvWx2vcHrtSy34or3X7gJ0\nlS8554t5AZotuVUp281N/8BiBEtDqig0lfbt6luZDqWxSgunjD1w8kpjGl4j2Aff\n2xbcG5bYhwKBgBbeLe5S921McaUNyLHEOuJJVXKaq/FoDFvM37J/pV2DUs6hF1bE\n3UqomkvzYIHrqVkn6YPhl9BatZ7dvp8CKnjiomcephzfuXTNKgkXzqc0rZsixGXB\n3g69trE1r3Rg07JBoP/8VMmPq7JtDYavHN6ROBPiA+ANpC/GWwGw6jdRAoGBAJrv\nTH6Z9cN4FNrzOCSduUAr/W4k1RE0bzPQWz+Vp1Bbkyu0gq2LNFMNzhkU0+gd4q1j\n2XOd/GGLWTr1IetJfwWdffXXBdU8TyTVnjcueMLB4NZ8AQNCsIMU9SmdeT9uu1Rb\n13AHlGiLYOSiraBgttYGVWbSM/PTqiu0g+dvBJJnAoGBAJ5RDdRWRoG4P9cPBKPs\nKMerkacC2mKCRifWQUWfintopTQboIv2NQlh2p7n6hsKNydjFMvt18rfa2X+RLSh\ncZvM/Ls5ccabb4RBFyhYBaXDvkXjRVCRu1fhOpVBqNgEwXmhAaJuSYj8b1JQEosi\nFredk7GNre3818CHC0jFXNee\n-----END PRIVATE KEY-----\n"
client_email="csac-service-account@phrasal-indexer-393802.iam.gserviceaccount.com"
client_id="108057524554855341997"
auth_uri="https://accounts.google.com/o/oauth2/auth"
token_uri="https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url="https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url="https://www.googleapis.com/robot/v1/metadata/x509/csac-service-account%40phrasal-indexer-393802.iam.gserviceaccount.com"
universe_domain="googleapis.com"
